<?php
//AUTO NUMBER SECTION
defined('FIRST_COUNTER_DB')     OR define('FIRST_COUNTER_DB', 100000000);

//OAA_ATTENDANCE_POINT
defined('AN_OAA_01_SEQ')      	OR define('AN_OAA_01_SEQ', '1');
defined('AN_OAA_01_DESC')      	OR define('AN_OAA_01_DESC', 'OAA_ATTENDANCE_POINT');
?>